name: 'Publish conda package using github action'
description: 'Publish Conda Package'
author: 'Ravin Poudel'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  CondaDir:
    description: 'Directory containing your meta.yml file'
    default: 'conda.recipe'
  Channels:
    description: 'Channels to use'
    default: 'conda-forge'
  Platforms: 
    description: 'input plaftorms'
    default: 'osx-64 linux-32 linux-64 win-32 win-64'
  CondaUsername:
    description: 'conda Username'
    required: true
  CondaPassword:
    description: 'conda Password'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'