name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Ravin Poudel'

branding:
  icon: 'package'  
  color: 'purple'

inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
  platforms:
    description: 'Platforms to publish [osx/linux/win]'
    default: 'osx linux win'
    
runs:
  using: 'docker'
  image: 'Dockerfile'